remote_theme: "mmistakes/minimal-mistakes@4.28.1"
title: "Julia Worthington"
subtitle: "Math and Dance Educator in Boulder, CO"
plugins:
  - jekyll-include-cache
minimal_mistakes_skin: "neon"
layout: single
defaults:
  # _docs
  - scope:
      path: ""
      type: docs
    values:
      sidebar:
        nav: "docs"
